sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t austynyou/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true austynyou/react-test npm run test

after_success:
  - docker build -t austynyou/multi-client ./client
  - docker build -t austynyou/multi-nginx ./nginx 
  - docker build -t austynyou/multi-server ./server
  - docker build -t austynyou/multi-worker  ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push austynyou/multi-client
  - docker push austynyou/multi-nginx
  - docker push austynyou/multi-server
  - docker push austynyou/multi-worker